"""empty message

Revision ID: 935fa0350de5
Revises: 
Create Date: 2019-05-14 10:55:07.441054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935fa0350de5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_ibfk_1', 'Event', type_='foreignkey')
    op.create_foreign_key(None, 'Event', 'User', ['host_id'], ['user_id'])
    op.drop_constraint('user_event_ibfk_1', 'User_Event', type_='foreignkey')
    op.drop_constraint('user_event_ibfk_2', 'User_Event', type_='foreignkey')
    op.create_foreign_key(None, 'User_Event', 'User', ['attendee_id'], ['user_id'])
    op.create_foreign_key(None, 'User_Event', 'Event', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User_Event', type_='foreignkey')
    op.drop_constraint(None, 'User_Event', type_='foreignkey')
    op.create_foreign_key('user_event_ibfk_2', 'User_Event', 'event', ['event_id'], ['event_id'])
    op.create_foreign_key('user_event_ibfk_1', 'User_Event', 'user', ['attendee_id'], ['user_id'])
    op.drop_constraint(None, 'Event', type_='foreignkey')
    op.create_foreign_key('event_ibfk_1', 'Event', 'user', ['host_id'], ['user_id'])
    # ### end Alembic commands ###
